### PR TITLE
New feature for issue #23: Alert for messages more than 1000 characters added.

### PR DESCRIPTION
**Pull request by shaahin**
Splits messages with more than 1000 characters to 1000 characters long message parts and send them separately.

### CODE REVIEW

**Review by Goga-Barabadze — CHANGES_REQUESTED** [review]
issue #23 also implies the splitting of the message itself. Not only the warning. Basically if the message is 1500 chars long. We split it into a 1000 char and a 500 char message and just send them separately

**Comment by shaahin** [comment]
Dear Goza
Thanks for your comment. I am working on it and will update my PR.

**Comment by shaahin** [comment]
@Goga-Barabadze would you please review my changes?

**Comment by Goga-Barabadze** [comment]
I checked it. We get a crash. `updateTableView` is not configured to handle more than one message at a time. 

```
private func updateTableView(animated: Bool){
        
        let indexPath = NSIndexPath(row: tableView.numberOfRows(inSection: 0), section: 0) as IndexPath
        tableView.insertRows(at: [indexPath], with: UITableView.RowAnimation.automatic)
        
        scrollToBottom(animated: true)
    }
```

I assume the error occurs because of this function due to the `NSIndexPath(row: tableView.numberOfRows(inSection: 0), section: 0)`. I could be wrong though

**Comment by shaahin** [comment]
It is now fixed. I moved `updateTableView` to update table after sending each message.
I ran it without any problems. Please review it again @Goga-Barabadze

**Comment by shaahin** [comment]
Dear @Goga-Barabadze, Would you please review my PR again?

**Pull request closed without merging**
